from enum import StrEnum, auto


class TableEnums(StrEnum):
    TABLEENDPOINTURL = "/api/now/table/"
    INCIDENT = "incident"
    SN_CUSTOMERSERVICE_CASE = "sn_customerservice_case"
    TASK = "task"
    M2M_KB_TASK = "m2m_kb_task"
    SYS_USER='sys_user'


class TaskEnums(StrEnum):
    ACTIVE = "active"
    ACTIVITY_DUE = "activity_due"
    ADDITIONAL_ASSIGNEE_LIST = "additional_assignee_list"
    APPROVAL = "approval"
    APPROVAL_HISTORY = "approval_history"
    APPROVAL_SET = "approval_set"
    ASSIGNED_TO = "assigned_to"
    ASSIGNMENT_GROUP = "assignment_group"
    BUSINESS_DURATION = "business_duration"
    BUSINESS_SERVICE = "business_service"
    CALENDAR_DURATION = "calendar_duration"
    CLOSE_NOTES = "close_notes"
    CLOSED_AT = "closed_at"
    CLOSED_BY = "closed_by"
    CMDB_CI = "cmdb_ci"
    COMMENTS = "comments"
    COMMENTS_AND_WORK_NOTES = "comments_and_work_notes"
    COMPANY = "company"
    CONTACT_TYPE = "contact_type"
    CONTRACT = "contract"
    CORRELATION_DISPLAY = "correlation_display"
    CORRELATION_ID = "correlation_id"
    DELIVERY_PLAN = "delivery_plan"
    DELIVERY_TASK = "delivery_task"
    DESCRIPTION = "description"
    DUE_DATE = "due_date"
    ESCALATION = "escalation"
    EXPECTED_START = "expected_start"
    FOLLOW_UP = "follow_up"
    GROUP_LIST = "group_list"
    IMPACT = "impact"
    KNOWLEDGE = "knowledge"
    LOCATION = "location"
    MADE_SLA = "made_sla"
    NUMBER = "number"
    OPENED_AT = "opened_at"
    OPENED_BY = "opened_by"
    ORDER = "order"
    PARENT = "parent"
    PRIORITY = "priority"
    REASSIGNMENT_COUNT = "reassignment_count"
    ROUTE_REASON = "route_reason"
    SERVICE_OFFERING = "service_offering"
    SHORT_DESCRIPTION = "short_description"
    SKILLS = "skills"
    SLA_DUE = "sla_due"
    STATE = "state"
    SYS_CLASS_NAME = "sys_class_name"
    SYS_CREATED_BY = "sys_created_by"
    SYS_CREATED_ON = "sys_created_on"
    SYS_DOMAIN = "sys_domain"
    SYS_DOMAIN_PATH = "sys_domain_path"
    SYS_ID = "sys_id"
    SYS_MOD_COUNT = "sys_mod_count"
    SYS_TAGS = "sys_tags"
    SYS_UPDATED_BY = "sys_updated_by"
    SYS_UPDATED_ON = "sys_updated_on"
    TASK_EFFECTIVE_NUMBER = "task_effective_number"
    TIME_WORKED = "time_worked"
    UNIVERSAL_REQUEST = "universal_request"
    UPON_APPROVAL = "upon_approval"
    UPON_REJECT = "upon_reject"
    URGENCY = "urgency"
    USER_INPUT = "user_input"
    WATCH_LIST = "watch_list"
    WORK_END = "work_end"
    WORK_NOTES = "work_notes"
    WORK_NOTES_LIST = "work_notes_list"
    WORK_START = "work_start"


class CsEnums(StrEnum):
    ACCOUNT = "account"
    ACTIVE = "active"
    ACTIVE_ACCOUNT_ESCALATION = "active_account_escalation"
    ACTIVE_ESCALATION = "active_escalation"
    ACTIVITY_DUE = "activity_due"
    ADDITIONAL_ASSIGNEE_LIST = "additional_assignee_list"
    APPROVAL = "approval"
    APPROVAL_HISTORY = "approval_history"
    APPROVAL_SET = "approval_set"
    ASSET = "asset"
    ASSIGNED_ON = "assigned_on"
    ASSIGNED_TO = "assigned_to"
    ASSIGNMENT_GROUP = "assignment_group"
    AUTO_CLOSE = "auto_close"
    BUSINESS_DURATION = "business_duration"
    BUSINESS_SERVICE = "business_service"
    CALENDAR_DURATION = "calendar_duration"
    CASE = "case"
    CASE_REPORT = "case_report"
    CATEGORY = "category"
    CAUSE = "cause"
    CAUSED_BY = "caused_by"
    CHANGE = "change"
    CLOSE_NOTES = "close_notes"
    CLOSED_AT = "closed_at"
    CLOSED_BY = "closed_by"
    CMDB_CI = "cmdb_ci"
    COMMENTS = "comments"
    COMMENTS_AND_WORK_NOTES = "comments_and_work_notes"
    COMPANY = "company"
    CONSUMER = "consumer"
    CONSUMER_PROFILE = "consumer_profile"
    CONTACT = "contact"
    CONTACT_LOCAL_TIME = "contact_local_time"
    CONTACT_TIME_ZONE = "contact_time_zone"
    CONTACT_TYPE = "contact_type"
    CONTRACT = "contract"
    CONTRIBUTOR_GROUPS = "contributor_groups"
    CONTRIBUTOR_USERS = "contributor_users"
    CORRELATION_DISPLAY = "correlation_display"
    CORRELATION_ID = "correlation_id"
    DELIVERY_PLAN = "delivery_plan"
    DELIVERY_TASK = "delivery_task"
    DESCRIPTION = "description"
    DUE_DATE = "due_date"
    ENTITLEMENT = "entitlement"
    ESCALATION = "escalation"
    EXPECTED_START = "expected_start"
    FIRST_RESPONSE_TIME = "first_response_time"
    FOLLOW_THE_SUN = "follow_the_sun"
    FOLLOW_UP = "follow_up"
    GROUP_LIST = "group_list"
    IMPACT = "impact"
    INCIDENT = "incident"
    INTERNAL_CONTACT = "internal_contact"
    INTERNAL_USER = "internal_user"
    KNOWLEDGE = "knowledge"
    LOCATION = "location"
    MADE_SLA = "made_sla"
    NOTES_TO_COMMENTS = "notes_to_comments"
    NOTIFY = "notify"
    NUMBER = "number"
    OPENED_AT = "opened_at"
    OPENED_BY = "opened_by"
    ORDER = "order"
    PARENT = "parent"
    PARTNER = "partner"
    PARTNER_CONTACT = "partner_contact"
    PRIORITY = "priority"
    PROACTIVE = "proactive"
    PROBLEM = "problem"
    PRODUCT = "product"
    REASSIGNMENT_COUNT = "reassignment_count"
    RELATED_PARTY_CONSUMERS = "related_party_consumers"
    RELATED_PARTY_USERS = "related_party_users"
    RESOLUTION_CODE = "resolution_code"
    RESOLVED_AT = "resolved_at"
    RESOLVED_BY = "resolved_by"
    ROUTE_REASON = "route_reason"
    SERVICE_OFFERING = "service_offering"
    SHORT_DESCRIPTION = "short_description"
    SKILLS = "skills"
    SLA_DUE = "sla_due"
    SN_APP_CS_SOCIAL_SOCIAL_PROFILE = "sn_app_cs_social_social_profile"
    STATE = "state"
    SUBCATEGORY = "subcategory"
    SUPPORT_MANAGER = "support_manager"
    SYNC_DRIVER = "sync_driver"
    SYS_CLASS_NAME = "sys_class_name"
    SYS_CREATED_BY = "sys_created_by"
    SYS_CREATED_ON = "sys_created_on"
    SYS_DOMAIN = "sys_domain"
    SYS_DOMAIN_PATH = "sys_domain_path"
    SYS_ID = "sys_id"
    SYS_MOD_COUNT = "sys_mod_count"
    SYS_TAGS = "sys_tags"
    SYS_UPDATED_BY = "sys_updated_by"
    SYS_UPDATED_ON = "sys_updated_on"
    TASK_EFFECTIVE_NUMBER = "task_effective_number"
    TIME_WORKED = "time_worked"
    UNIVERSAL_REQUEST = "universal_request"
    UPON_APPROVAL = "upon_approval"
    UPON_REJECT = "upon_reject"
    URGENCY = "urgency"
    USER_INPUT = "user_input"
    WATCH_LIST = "watch_list"
    WORK_END = "work_end"
    WORK_NOTES = "work_notes"
    WORK_NOTES_LIST = "work_notes_list"
    WORK_START = "work_start"


class StateEnums(StrEnum):
    NEW = "New"
    OPEN = "Open"
    AWAITING_INFO = "Awaiting Info"
    RESOLVED = "Resolved"
    CLOSED = "Closed"
    CANCELLED = "Cancelled"


class ResolutionCodeEnums(StrEnum):
    NONE = "1"
    SOLVED_SUPPORT = "2"
    SOLVED_PRB = "3"
    SOLVED_WORKAROUND = "4"
    SOLVED_CUSTOMER = "5"
    INCONCLUSIVE_SCOPE = "6"
    INCONCLUSIVE_REPRODUCE = "7"
    INCONCLUSIVE_WORKAROUND = "8"
    DUPLICATE = "9"
    VOIDED_CANCELLED = "10"
    SOLVED_CHANGE = "11"
    SOLVED_INCIDENT = "12"


class SysUserEnums(StrEnum):
    ACTIVE = "active"
    AVATAR = "avatar"
    BUILDING = "building"
    CALENDAR_INTEGRATION = "calendar_integration"
    CITY = "city"
    COMPANY = "company"
    COST_CENTER = "cost_center"
    COUNTRY = "country"
    DATE_FORMAT = "date_format"
    DEFAULT_PERSPECTIVE = "default_perspective"
    DEPARTMENT = "department"
    EMAIL = "email"
    EMPLOYEE_NUMBER = "employee_number"
    ENABLE_MULTIFACTOR_AUTHN = "enable_multifactor_authn"
    FAILED_ATTEMPTS = "failed_attempts"
    FIRST_NAME = "first_name"
    GENDER = "gender"
    HOME_PHONE = "home_phone"
    INTERNAL_INTEGRATION_USER = "internal_integration_user"
    INTRODUCTION = "introduction"
    LAST_LOGIN = "last_login"
    LAST_LOGIN_TIME = "last_login_time"
    LAST_NAME = "last_name"
    LDAP_SERVER = "ldap_server"
    LOCATION = "location"
    LOCKED_OUT = "locked_out"
    MANAGER = "manager"
    MIDDLE_NAME = "middle_name"
    MOBILE_PHONE = "mobile_phone"
    NAME = "name"
    NOTIFICATION = "notification"
    PASSWORD_NEEDS_RESET = "password_needs_reset"
    PHONE = "phone"
    PHOTO = "photo"
    PREFERRED_LANGUAGE = "preferred_language"
    ROLES = "roles"
    SCHEDULE = "schedule"
    SOURCE = "source"
    STATE = "state"
    STREET = "street"
    SYS_CLASS_NAME = "sys_class_name"
    SYS_CREATED_BY = "sys_created_by"
    SYS_CREATED_ON = "sys_created_on"
    SYS_DOMAIN = "sys_domain"
    SYS_DOMAIN_PATH = "sys_domain_path"
    SYS_ID = "sys_id"
    SYS_MOD_COUNT = "sys_mod_count"
    SYS_TAGS = "sys_tags"
    SYS_UPDATED_BY = "sys_updated_by"
    SYS_UPDATED_ON = "sys_updated_on"
    TIME_FORMAT = "time_format"
    TIME_ZONE = "time_zone"
    TITLE = "title"
    USER_NAME = "user_name"
    USER_PASSWORD = "user_password"
    VIP = "vip"
    WEB_SERVICE_ACCESS_ONLY = "web_service_access_only"
    ZIP = "zip"

class ApiUrlsEnums(StrEnum):
    CASETABLEAPI = "/api/now/table/sn_customerservice_case"
    TASKTABLEAPI = "/api/now/table/task"


class ResponseEnums(StrEnum):
    RESULT = "result"


class ConfigEnums(StrEnum):
    #
    BASE_FIELD = "base_field"
    COOKIES = "cookies"
    EMAIL_API = "email_api"
    ASSIGNED_TO_DEFAULT = "assigned_to_default"
    ASSIGNMENT_GROUP_DEFAULT = "assignment_group_default"
    DEFAULT_PARAMS_POST = "default_params_post"

class display_value_enums(StrEnum):
    TRUE='true'
    FALSE='false'
    ALL='all'