
from enum import StrEnum, auto

from ..common_utils import get_configs

configs:dict = get_configs()
class TableEnums(StrEnum):
    
    INCIDENT = 'incident'
    SN_CUSTOMERSERVICE_CASE = 'sn_customerservice_case'
    TASK = 'task'
    M2M_KB_TASK = 'm2m_kb_task'

class task_enums(StrEnum):
    
    ACTIVE='active'
    ACTIVITY_DUE='activity_due'
    ADDITIONAL_ASSIGNEE_LIST='additional_assignee_list'
    APPROVAL='approval'
    APPROVAL_HISTORY='approval_history'
    APPROVAL_SET='approval_set'
    ASSIGNED_TO='assigned_to'
    ASSIGNMENT_GROUP='assignment_group'
    BUSINESS_DURATION='business_duration'
    BUSINESS_SERVICE='business_service'
    CALENDAR_DURATION='calendar_duration'
    CLOSE_NOTES='close_notes'
    CLOSED_AT='closed_at'
    CLOSED_BY='closed_by'
    CMDB_CI='cmdb_ci'
    COMMENTS='comments'
    COMMENTS_AND_WORK_NOTES='comments_and_work_notes'
    COMPANY='company'
    CONTACT_TYPE='contact_type'
    CONTRACT='contract'
    CORRELATION_DISPLAY='correlation_display'
    CORRELATION_ID='correlation_id'
    DELIVERY_PLAN='delivery_plan'
    DELIVERY_TASK='delivery_task'
    DESCRIPTION='description'
    DUE_DATE='due_date'
    ESCALATION='escalation'
    EXPECTED_START='expected_start'
    FOLLOW_UP='follow_up'
    GROUP_LIST='group_list'
    IMPACT='impact'
    KNOWLEDGE='knowledge'
    LOCATION='location'
    MADE_SLA='made_sla'
    NUMBER='number'
    OPENED_AT='opened_at'
    OPENED_BY='opened_by'
    ORDER='order'
    PARENT='parent'
    PRIORITY='priority'
    REASSIGNMENT_COUNT='reassignment_count'
    ROUTE_REASON='route_reason'
    SERVICE_OFFERING='service_offering'
    SHORT_DESCRIPTION='short_description'
    SKILLS='skills'
    SLA_DUE='sla_due'
    STATE='state'
    SYS_CLASS_NAME='sys_class_name'
    SYS_CREATED_BY='sys_created_by'
    SYS_CREATED_ON='sys_created_on'
    SYS_DOMAIN='sys_domain'
    SYS_DOMAIN_PATH='sys_domain_path'
    SYS_ID='sys_id'
    SYS_MOD_COUNT='sys_mod_count'
    SYS_TAGS='sys_tags'
    SYS_UPDATED_BY='sys_updated_by'
    SYS_UPDATED_ON='sys_updated_on'
    TASK_EFFECTIVE_NUMBER='task_effective_number'
    TIME_WORKED='time_worked'
    UNIVERSAL_REQUEST='universal_request'
    UPON_APPROVAL='upon_approval'
    UPON_REJECT='upon_reject'
    URGENCY='urgency'
    USER_INPUT='user_input'
    WATCH_LIST='watch_list'
    WORK_END='work_end'
    WORK_NOTES='work_notes'
    WORK_NOTES_LIST='work_notes_list'
    WORK_START='work_start'

class cs_enums(StrEnum):
    ACCOUNT="account"
    ACTIVE="active"
    ACTIVE_ACCOUNT_ESCALATION="active_account_escalation"
    ACTIVE_ESCALATION="active_escalation"
    ACTIVITY_DUE="activity_due"
    ADDITIONAL_ASSIGNEE_LIST="additional_assignee_list"
    APPROVAL="approval"
    APPROVAL_HISTORY="approval_history"
    APPROVAL_SET="approval_set"
    ASSET="asset"
    ASSIGNED_ON="assigned_on"
    ASSIGNED_TO="assigned_to"
    ASSIGNMENT_GROUP="assignment_group"
    AUTO_CLOSE="auto_close"
    BUSINESS_DURATION="business_duration"
    BUSINESS_SERVICE="business_service"
    CALENDAR_DURATION="calendar_duration"
    CASE="case"
    CASE_REPORT="case_report"
    CATEGORY="category"
    CAUSE="cause"
    CAUSED_BY="caused_by"
    CHANGE="change"
    CLOSE_NOTES="close_notes"
    CLOSED_AT="closed_at"
    CLOSED_BY="closed_by"
    CMDB_CI="cmdb_ci"
    COMMENTS="comments"
    COMMENTS_AND_WORK_NOTES="comments_and_work_notes"
    COMPANY="company"
    CONSUMER="consumer"
    CONSUMER_PROFILE="consumer_profile"
    CONTACT="contact"
    CONTACT_LOCAL_TIME="contact_local_time"
    CONTACT_TIME_ZONE="contact_time_zone"
    CONTACT_TYPE="contact_type"
    CONTRACT="contract"
    CONTRIBUTOR_GROUPS="contributor_groups"
    CONTRIBUTOR_USERS="contributor_users"
    CORRELATION_DISPLAY="correlation_display"
    CORRELATION_ID="correlation_id"
    DELIVERY_PLAN="delivery_plan"
    DELIVERY_TASK="delivery_task"
    DESCRIPTION="description"
    DUE_DATE="due_date"
    ENTITLEMENT="entitlement"
    ESCALATION="escalation"
    EXPECTED_START="expected_start"
    FIRST_RESPONSE_TIME="first_response_time"
    FOLLOW_THE_SUN="follow_the_sun"
    FOLLOW_UP="follow_up"
    GROUP_LIST="group_list"
    IMPACT="impact"
    INCIDENT="incident"
    INTERNAL_CONTACT="internal_contact"
    INTERNAL_USER="internal_user"
    KNOWLEDGE="knowledge"
    LOCATION="location"
    MADE_SLA="made_sla"
    NOTES_TO_COMMENTS="notes_to_comments"
    NOTIFY="notify"
    NUMBER="number"
    OPENED_AT="opened_at"
    OPENED_BY="opened_by"
    ORDER="order"
    PARENT="parent"
    PARTNER="partner"
    PARTNER_CONTACT="partner_contact"
    PRIORITY="priority"
    PROACTIVE="proactive"
    PROBLEM="problem"
    PRODUCT="product"
    REASSIGNMENT_COUNT="reassignment_count"
    RELATED_PARTY_CONSUMERS="related_party_consumers"
    RELATED_PARTY_USERS="related_party_users"
    RESOLUTION_CODE="resolution_code"
    RESOLVED_AT="resolved_at"
    RESOLVED_BY="resolved_by"
    ROUTE_REASON="route_reason"
    SERVICE_OFFERING="service_offering"
    SHORT_DESCRIPTION="short_description"
    SKILLS="skills"
    SLA_DUE="sla_due"
    SN_APP_CS_SOCIAL_SOCIAL_PROFILE="sn_app_cs_social_social_profile"
    STATE="state"
    SUBCATEGORY="subcategory"
    SUPPORT_MANAGER="support_manager"
    SYNC_DRIVER="sync_driver"
    SYS_CLASS_NAME="sys_class_name"
    SYS_CREATED_BY="sys_created_by"
    SYS_CREATED_ON="sys_created_on"
    SYS_DOMAIN="sys_domain"
    SYS_DOMAIN_PATH="sys_domain_path"
    SYS_ID="sys_id"
    SYS_MOD_COUNT="sys_mod_count"
    SYS_TAGS="sys_tags"
    SYS_UPDATED_BY="sys_updated_by"
    SYS_UPDATED_ON="sys_updated_on"
    TASK_EFFECTIVE_NUMBER="task_effective_number"
    TIME_WORKED="time_worked"
    UNIVERSAL_REQUEST="universal_request"
    UPON_APPROVAL="upon_approval"
    UPON_REJECT="upon_reject"
    URGENCY="urgency"
    USER_INPUT="user_input"
    WATCH_LIST="watch_list"
    WORK_END="work_end"
    WORK_NOTES="work_notes"
    WORK_NOTES_LIST="work_notes_list"
    WORK_START="work_start"

class state_enums(StrEnum):
    NEW='New'
    OPEN='Open'
    AWAITING_INFO='Awaiting Info'
    RESOLVED='Resolved'
    CLOSED='Closed'
    CANCELLED='Cancelled'

class resolution_code_enums(StrEnum):
    NONE = "1"
    SOLVED_SUPPORT = "2"
    SOLVED_PRB = "3"
    SOLVED_WORKAROUND = "4"
    SOLVED_CUSTOMER = "5"
    INCONCLUSIVE_SCOPE = "6"
    INCONCLUSIVE_REPRODUCE = "7"
    INCONCLUSIVE_WORKAROUND = "8"
    DUPLICATE = "9"
    VOIDED_CANCELLED = "10"
    SOLVED_CHANGE = "11"
    SOLVED_INCIDENT = "12"

# class ApiUrls(StrEnum):
    
#     mailapi=configs['email_api']
#     casetableapi=configs['/api/now/table/sn_customerservice_case']
    
    