# Generated by Django 4.1.7 on 2023-03-08 18:06

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Cookie",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.TextField(blank=True, null=True, unique=True)),
                ("value", models.TextField(blank=True, null=True)),
                ("domain", models.TextField(blank=True, null=True)),
                ("path", models.TextField(blank=True, null=True)),
                ("expires", models.TextField(blank=True, null=True)),
                ("httpOnly", models.TextField(blank=True, null=True)),
                ("secure", models.TextField(blank=True, null=True)),
                ("sameSite", models.TextField(blank=True, null=True)),
                ("notes", models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name="Header",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.TextField(default="head", unique=True)),
                ("value", models.JSONField(blank=True, null=True)),
            ],
        ),
    ]
